#!/usr/bin/env python3
"""Compile a validated Kubrick design-specification artifact into design.md."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyYAML is required: python -m pip install pyyaml") from exc


def load_data(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    data = json.loads(text) if path.suffix.lower() == ".json" else yaml.safe_load(text)
    if not isinstance(data, dict):
        raise ValueError("design specification root must be an object")
    return data


def require(data: dict[str, Any], key: str) -> Any:
    value = data.get(key)
    if value is None or value == "" or value == []:
        raise ValueError(f"missing required field: {key}")
    return value


def bullets(values: list[Any], empty: str = "NOT_COMPUTABLE") -> str:
    if not values:
        return f"- {empty}"
    return "\n".join(f"- {value}" for value in values)


def table(rows: list[list[str]], headers: list[str]) -> str:
    divider = ["---"] * len(headers)
    all_rows = [headers, divider, *rows]
    return "\n".join("| " + " | ".join(str(cell).replace("\n", " ") for cell in row) + " |" for row in all_rows)


def compile_markdown(data: dict[str, Any]) -> str:
    project = require(data, "project")
    authority = require(data, "authority")
    intent = require(data, "design_intent")
    pillars = require(data, "pillars")
    invariants = require(data, "invariants")
    experience = require(data, "experience")
    systems = data.get("systems", [])
    languages = require(data, "design_languages")
    continuity = require(data, "continuity_contract")
    risks = data.get("risks", [])
    questions = data.get("open_questions", [])

    pillar_rows = [[p["id"], p["statement"], p["test"], p.get("provenance", "INFERRED")] for p in pillars]
    invariant_rows = [[i["id"], i["rule"], i["verification"], i.get("severity", "medium")] for i in invariants]
    system_rows = [
        [
            s["id"],
            s["purpose"],
            ", ".join(s.get("inputs", [])),
            ", ".join(s.get("outputs", [])),
            ", ".join(s.get("constraints", [])),
        ]
        for s in systems
    ]
    risk_rows = [[r["risk"], r["signal"], r["mitigation"]] for r in risks]
    question_rows = [[q["question"], "yes" if q["blocking"] else "no", q.get("resolution_owner", "unassigned")] for q in questions]

    sections = [
        f"# {project['name']} — Design Specification",
        "",
        "> Generated by Kubrick from a schema-validated design specification. This document is not canonical unless explicitly promoted by an authorized operator.",
        "",
        "## Authority",
        "",
        f"- **Status:** `{authority['status']}`",
        f"- **Artifact type:** `{project['artifact_type']}`",
        f"- **Version:** `{project.get('version', 'unversioned')}`",
        f"- **Source revision:** `{authority.get('source_revision', 'NOT_COMPUTABLE')}`",
        "",
        "## Design Intent",
        "",
        f"**Premise:** {intent['premise']}",
        "",
        f"**Governing tension:** {intent['governing_tension']}",
        "",
        f"**Intended transformation:** {intent['intended_transformation']}",
        "",
        "### Non-goals",
        "",
        bullets(intent.get("non_goals", []), "None declared"),
        "",
        "## Design Pillars",
        "",
        table(pillar_rows, ["ID", "Pillar", "Verification test", "Provenance"]),
        "",
        "## Invariants",
        "",
        table(invariant_rows, ["ID", "Rule", "Verification", "Severity"]),
        "",
        "## Intended Experience",
        "",
        f"**User state:** {experience['user_state']}",
        "",
        "### Core loop",
        "",
        bullets(experience["core_loop"]),
        "",
        "### Emotional arc",
        "",
        bullets(experience["emotional_arc"]),
        "",
        f"**Failure experience:** {experience['failure_experience']}",
        "",
        f"**Success experience:** {experience.get('success_experience', 'NOT_COMPUTABLE')}",
        "",
        "## Systems",
        "",
        table(system_rows, ["System", "Purpose", "Inputs", "Outputs", "Constraints"]) if system_rows else "- NOT_COMPUTABLE",
        "",
        "## Design Languages",
    ]

    for name in ["visual", "interaction", "audio", "narrative", "motion"]:
        language = languages[name]
        sections.extend([
            "",
            f"### {name.title()}",
            "",
            "**Principles**",
            "",
            bullets(language.get("principles", [])),
            "",
            "**Motifs**",
            "",
            bullets(language.get("motifs", []), "None declared"),
            "",
            "**Avoid**",
            "",
            bullets(language.get("avoid", [])),
        ])

    sections.extend([
        "",
        "## Continuity Contract",
        "",
        "### Locked facts",
        "",
        bullets(continuity["locked_facts"]),
        "",
        "### Mutable variables",
        "",
        bullets(continuity["mutable_variables"]),
        "",
        "### Prohibited drift",
        "",
        bullets(continuity["prohibited_drift"]),
        "",
        f"**Revision protocol:** {continuity['revision_protocol']}",
        "",
        "## Risks",
        "",
        table(risk_rows, ["Risk", "Detection signal", "Mitigation"]) if risk_rows else "- None declared",
        "",
        "## Open Questions",
        "",
        table(question_rows, ["Question", "Blocking", "Owner"]) if question_rows else "- None declared",
        "",
        "## Provenance",
        "",
    ])

    for source in require(data, "observed_inputs"):
        sections.append(f"- `{source['provenance']}` — {source['kind']}: {source['source']}" + (f" @ {source['revision']}" if source.get("revision") else ""))

    sections.extend([
        "",
        "## Drift Rule",
        "",
        "A revision that changes a locked fact, invariant, pillar verification test, or prohibited-drift rule must emit an explicit revision delta. Silent replacement is invalid.",
        "",
    ])
    return "\n".join(sections)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile Kubrick design specification YAML/JSON into design.md")
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    data = load_data(args.input)
    markdown = compile_markdown(data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")
    print(json.dumps({"status": "PROPOSED", "output": str(args.output), "project": data["project"]["name"]}, sort_keys=True))


if __name__ == "__main__":
    main()
